console.log(5 && 6)
console.log(0 || 6)
console.log("яблоки" || "не яблоки")
console.log("Alex" || "")
console.log(false || "")
console.log(!!1)
console.log(!1)
console.log(!!(5*5))
console.log(!(5*5))
console.log("") // НИЧЕГО НЕТУ В ЭТОЙ СТРОКЕ